version: "3.8"

services:
  backend:
    build: ./backend
    # command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend/:/usr/src/frontend/
  #   ports:
  #     - 3000:80
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=toanh
      - POSTGRES_PASSWORD=toanh
      - POSTGRES_DB=bv_phutho
      - PGPORT=5432
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  pgadmin-data:
  postgres_data:
