# Generated by Django 4.2.6 on 2023-11-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, unique=True)),
                ('department_code', models.CharField(max_length=50, unique=True)),
                ('isCenterDepartment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='TypeOfDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'TypeOfDepartment',
            },
        ),
        migrations.CreateModel(
            name='RoomDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomDepartment_code', models.CharField(max_length=50, null=True, unique=True)),
                ('roomDepartment_name', models.CharField(max_length=200, unique=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='departments.departmentmodel')),
            ],
            options={
                'db_table': 'RoomDepartment',
            },
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='typeOfDepartment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeOfDepartment_id', to='departments.typeofdepartmentmodel'),
        ),
    ]
