# Generated by Django 4.2.6 on 2023-11-03 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, unique=True)),
                ('department_code', models.CharField(max_length=50, unique=True)),
                ('isCenterDepartment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='RoomDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomDepartment_code', models.CharField(max_length=50, null=True, unique=True)),
                ('roomDepartment_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'RoomDepartments',
            },
        ),
        migrations.CreateModel(
            name='TypeOfDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'TypesOfDepartment',
                'indexes': [models.Index(fields=['type_name'], name='TypesOfDepa_type_na_79fd88_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='typeofdepartmentmodel',
            constraint=models.UniqueConstraint(fields=('type_name',), name='unique_type_name'),
        ),
        migrations.AddField(
            model_name='roomdepartmentmodel',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='departments.departmentmodel', verbose_name='Id của table Departments'),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='typeOfDepartment_id',
            field=models.ForeignKey(db_column='typeOfDepartment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeOfDepartment_id', to='departments.typeofdepartmentmodel', verbose_name='Id của table TypesOfDepartment'),
        ),
        migrations.AddIndex(
            model_name='roomdepartmentmodel',
            index=models.Index(fields=['department_id', 'roomDepartment_code'], name='RoomDepartm_departm_96373e_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomdepartmentmodel',
            constraint=models.UniqueConstraint(fields=('roomDepartment_name',), name='unique_roomDepartment_name'),
        ),
        migrations.AddConstraint(
            model_name='roomdepartmentmodel',
            constraint=models.UniqueConstraint(fields=('roomDepartment_code',), name='unique_roomDepartment_code'),
        ),
        migrations.AddIndex(
            model_name='departmentmodel',
            index=models.Index(fields=['typeOfDepartment_id', 'department_code'], name='Departments_typeOfD_a18626_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentmodel',
            constraint=models.UniqueConstraint(fields=('department_name',), name='unique_department_name'),
        ),
        migrations.AddConstraint(
            model_name='departmentmodel',
            constraint=models.UniqueConstraint(fields=('department_code',), name='unique_department_code'),
        ),
    ]
