# Generated by Django 4.2.6 on 2023-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdepartmentmodel',
            name='roomDepartment_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
