# Generated by Django 4.2.6 on 2023-11-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roomdepartmentmodel',
            new_name='RoomDepartm_typeOfD_d3eaef_idx',
            old_name='RoomDepartm_typeOfD_02a48a_idx',
        ),
        migrations.AlterField(
            model_name='roomdepartmentmodel',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_id', to='departments.departmentmodel', verbose_name='Id của table Departments'),
        ),
        migrations.AlterField(
            model_name='roomdepartmentmodel',
            name='typeOfDepartment_id',
            field=models.ForeignKey(db_column='typeOfDepartment_id', on_delete=django.db.models.deletion.CASCADE, related_name='typeOfDepartment_id', to='departments.typeofdepartmentmodel', verbose_name='Id của table TypesOfDepartment'),
        ),
    ]
