# Generated by Django 4.2.6 on 2023-11-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='typeOfDepartment_id',
        ),
        migrations.AddField(
            model_name='roomdepartmentmodel',
            name='typeOfDepartment_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='typeOfDepartment_id', to='departments.typeofdepartmentmodel'),
            preserve_default=False,
        ),
    ]
