# Generated by Django 4.2.6 on 2023-11-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_departmentmodel_typeofdepartment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdepartmentmodel',
            name='department_id',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_id', to='departments.departmentmodel'),
        ),
    ]
