# Generated by Django 4.2.6 on 2023-11-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_roomdepartm_typeofd_02a48a_idx_roomdepartm_typeofd_d3eaef_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='isCenterDepartment',
            field=models.BooleanField(default=False),
        ),
    ]
