# Generated by Django 4.2.6 on 2023-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_roomdepartmentmodel_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='isCenterDepartment',
        ),
        migrations.AlterField(
            model_name='roomdepartmentmodel',
            name='roomDepartment_code',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
