# Generated by Django 4.2.6 on 2023-11-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_departmentmodel_iscenterdepartment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='departmentmodel',
            name='Departments_departm_f3b70d_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomdepartmentmodel',
            name='RoomDepartm_typeOfD_d3eaef_idx',
        ),
        migrations.RemoveField(
            model_name='roomdepartmentmodel',
            name='typeOfDepartment_id',
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='typeOfDepartment_id',
            field=models.ForeignKey(db_column='typeOfDepartment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeOfDepartment_id', to='departments.typeofdepartmentmodel', verbose_name='Id của table TypesOfDepartment'),
        ),
        migrations.AlterField(
            model_name='roomdepartmentmodel',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='departments.departmentmodel', verbose_name='Id của table Departments'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='departmentmodel',
            index=models.Index(fields=['typeOfDepartment_id', 'department_code'], name='Departments_typeOfD_a18626_idx'),
        ),
        migrations.AddIndex(
            model_name='roomdepartmentmodel',
            index=models.Index(fields=['department_id', 'roomDepartment_code'], name='RoomDepartm_departm_96373e_idx'),
        ),
    ]
