# Generated by Django 4.2.6 on 2023-11-02 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_roomdepartm_typeofd_02a48a_idx_roomdepartm_typeofd_d3eaef_idx_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roomdepartmentroleusermodel',
            new_name='RoomDepartm_roomDep_d1ad0c_idx',
            old_name='RoomDepartm_roomDep_9999c6_idx',
        ),
        migrations.AlterField(
            model_name='roomdepartmentroleusermodel',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_id', to='users.rolemodel', verbose_name='Id của table Roles'),
        ),
        migrations.AlterField(
            model_name='roomdepartmentroleusermodel',
            name='roomDepartment_id',
            field=models.ForeignKey(db_column='roomDepartment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomDepartment_id', to='departments.roomdepartmentmodel', verbose_name='Id của table RoomDepartments'),
        ),
        migrations.AlterField(
            model_name='roomdepartmentroleusermodel',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='Id của table Users'),
        ),
    ]
