# Generated by Django 4.2.6 on 2023-10-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='Users',
        ),
    ]
