# Generated by Django 4.2.6 on 2023-10-22 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='department',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='users.departments'),
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='department',
            new_name='department_id',
        ),
    ]
